### ISSUE TITLE
SSL not working

### ISSUE THREAD

**Issue by si458** [mancuniancol/script.pulsar.kickass-mc#2]
16:10:11 921.308289 T:1465902144  NOTICE: [script.pulsar.kickass-mc] https://kickass.unblocked.la/usearch/minions%202015/?field=seeders&sorder=desc
16:10:12 922.622192 T:1465902144   ERROR: [script.pulsar.kickass-mc] >>>>>>>[Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error<<<<<<<

it appears its being redirected to SSL which the script doesnt like :( 

any ideas how to fix as kickass now only seems to use SSL

**Comment by mancuniancol** [comment]
Yes, python doesn't work well under openssl. You need to find a mirror http instead. . I've tried different ways, but without luck.

**Comment by si458** [comment]
its very weird because it works fine with openelec 5.0.8 but not the new 6.0.0 ?
im using a raspberry pi as well

**Comment by mancuniancol** [comment]
I've found a way to deal with https.  But you will need to install couple modules
script.module.requests
script.module.pyopenssl

if you use the repo, it will install those dependencies automatic
